[conquest]
[conquest.1]
[conquest.1.sql]
mysql_uri = "mysql+pymysql://root:BestefarKjeksKaffe@localhost/conquest_1"

[conquest.1.dicom]
aet = "MEDFYSHUS6666-1"
server = "127.0.0.1"
port = 57863

[conquest.2]
[conquest.2.sql]
mysql_uri = "mysql+pymysql://root:BestefarKjeksKaffe@localhost/conquest_2"
data_dir = "D:/Conquest/MEDFYSHUS6666-2/data"

[conquest.2.dicom]
aet = "MEDFYSHUS6666-2"
server = "127.0.0.1"
port = 31416

[aria]
[aria.sql]
uri = "mssql+pyodbc://VIR-APP5338/localrtdb?driver=SQL+Server"

[aria.dicom]
aet = "VMSDBD"
port = 57347
server = "VIR-APP5340"

[log_db]
sql_uri = "mssql+pyodbc://AGBGODNCA2/ProtonRegister_prod?driver=SQL+Server"

[krest]
aet = "GW_HUS"
port = 31416
server = "10.53.252.160"