[conquest_aria]
root_dir = "D:/Conquest/MEDFYSHUS6666-1/data/"

[conquest_aria.sql]
uri = "mysql+pymysql://root:BestefarKjeksKaffe@localhost/conquest_1"

[conquest_aria.dicom]
aet = "MEDFYSHUS6666-1"
server = "127.0.0.1"
port = 57863

[conquest_krest]
root_dir = "D:/Conquest/MEDFYSHUS6666-2/data/"
[conquest_krest.sql]
uri = "mysql+pymysql://root:BestefarKjeksKaffe@localhost/conquest_2"

[conquest_krest.dicom]
aet = "MEDFYSHUS6666-2"
server = "127.0.0.1"
port = 31416

[aria]
[aria.sql]
uri = "mssql+pyodbc://VIR-APP5338/VARIAN?driver=SQL+Server"

[aria.dicom]
aet = "VMSDBD"
port = 57347
server = "VIR-APP5340"

[log_db]
uri = ""
file = "log_db/patient_log.json"

[krest]
name = "KREST-HUS"
[krest.dicom]
aet = "GW_HUS"